### ISSUE TITLE
Search page story - get all transactons for specific address

### ISSUE THREAD

**Issue by abitrolly** [asadovka/cyb_web2#35]
As analyst I want to get all transactions for specific address (ETH). By @Snedashkovsky.

---

We've discussed that downloading CSV is way better than clicking through pages and gathering data through them. We may even just expose CSV export to API. The link for to download that CSV from API would still be useful in UI.

**Comment by abitrolly** [comment]
Evaluation. Backend is ready - we've got current API `/ethereum/address/{address}/transactions`. We need to test what is returned by it, add docs, test what happens if transactions are included in uncle (orphan). Concern is about indexing chain. We don't have metrics about ETH indexation process and last time we've checked indexation crashed.

**Comment by abitrolly** [comment]
* [ ] API is there, but nobody tested it
* [ ] check docs - users can discover API, where is our Swagger
* [ ] add CSV export if JSON is not enough (UI)
* [ ] add data quality check - compare last block with last indexed block and show status

Stress test - get all transactions from market.

**Comment by abitrolly** [comment]
From UI side we make page for specific (ETH) `/ethereum/address/0xXXXXX` and place a link with to CSV to download all transactions there.

**Comment by abitrolly** [comment]
* [x] indexing ETH didn't work, because if component (Cassandra, Ethereum node) was lost, `chainpump` (and `search-api`) was waiting for them and then fell down by timeout - @YodaMike fixed this for `chainpump`

Indexing still doesn't work:

* [x] Ethereum Classic indexing breaks always at certain block https://github.com/cyberFund/cyber-search/issues/32
* [ ] Bitcoin indexing breaks after 220k - `bitcoind` daemon crashes when we get data for all transaction hashes from one block - https://github.com/cyberFund/cyber-search/issues/34
* [x] `address service` - is a Kafka plugin that calculates balance delta per block and tx (with reorganization) - it hangs and needs pictures (!!!) - https://github.com/cyberFund/cyber-search/issues/36

* [ ] indexing needs to be LIVE - right now our indexer didn't get to the end of chain (sync graph?)

**Comment by hleb-albau** [comment]
Also, current implementation return last 20 transactions for address(ad-hoc). We should redesign app, to provide offset and count query params.

**Comment by cyborgshead** [comment]
@litvintech @abitrolly need to migrate story to cybernode
and provide reasons for this, also text to story customer about migration
